#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStudentLocation(StudentLocation instance);
    partial void UpdateStudentLocation(StudentLocation instance);
    partial void DeleteStudentLocation(StudentLocation instance);
    partial void Insertthongtinhocsinh(thongtinhocsinh instance);
    partial void Updatethongtinhocsinh(thongtinhocsinh instance);
    partial void Deletethongtinhocsinh(thongtinhocsinh instance);
    partial void InsertFileInfo(FileInfo instance);
    partial void UpdateFileInfo(FileInfo instance);
    partial void DeleteFileInfo(FileInfo instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["testConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StudentLocation> StudentLocations
		{
			get
			{
				return this.GetTable<StudentLocation>();
			}
		}
		
		public System.Data.Linq.Table<chedouutien> chedouutiens
		{
			get
			{
				return this.GetTable<chedouutien>();
			}
		}
		
		public System.Data.Linq.Table<hocba> hocbas
		{
			get
			{
				return this.GetTable<hocba>();
			}
		}
		
		public System.Data.Linq.Table<hosodinhkem> hosodinhkems
		{
			get
			{
				return this.GetTable<hosodinhkem>();
			}
		}
		
		public System.Data.Linq.Table<thongtinhocsinh> thongtinhocsinhs
		{
			get
			{
				return this.GetTable<thongtinhocsinh>();
			}
		}
		
		public System.Data.Linq.Table<FileInfo> FileInfos
		{
			get
			{
				return this.GetTable<FileInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentLocation")]
	public partial class StudentLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAddress;
		
		private string _NameAddress;
		
		private int _ParentId;
		
		private int _LevelAddress;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedUser;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
		private string _UpdatedUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAddressChanging(int value);
    partial void OnIdAddressChanged();
    partial void OnNameAddressChanging(string value);
    partial void OnNameAddressChanged();
    partial void OnParentIdChanging(int value);
    partial void OnParentIdChanged();
    partial void OnLevelAddressChanging(int value);
    partial void OnLevelAddressChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedUserChanging(string value);
    partial void OnCreatedUserChanged();
    partial void OnUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateChanged();
    partial void OnUpdatedUserChanging(string value);
    partial void OnUpdatedUserChanged();
    #endregion
		
		public StudentLocation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAddress", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAddress
		{
			get
			{
				return this._IdAddress;
			}
			set
			{
				if ((this._IdAddress != value))
				{
					this.OnIdAddressChanging(value);
					this.SendPropertyChanging();
					this._IdAddress = value;
					this.SendPropertyChanged("IdAddress");
					this.OnIdAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameAddress", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string NameAddress
		{
			get
			{
				return this._NameAddress;
			}
			set
			{
				if ((this._NameAddress != value))
				{
					this.OnNameAddressChanging(value);
					this.SendPropertyChanging();
					this._NameAddress = value;
					this.SendPropertyChanged("NameAddress");
					this.OnNameAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int NOT NULL")]
		public int ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelAddress", DbType="Int NOT NULL")]
		public int LevelAddress
		{
			get
			{
				return this._LevelAddress;
			}
			set
			{
				if ((this._LevelAddress != value))
				{
					this.OnLevelAddressChanging(value);
					this.SendPropertyChanging();
					this._LevelAddress = value;
					this.SendPropertyChanged("LevelAddress");
					this.OnLevelAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUser", DbType="NVarChar(250)")]
		public string CreatedUser
		{
			get
			{
				return this._CreatedUser;
			}
			set
			{
				if ((this._CreatedUser != value))
				{
					this.OnCreatedUserChanging(value);
					this.SendPropertyChanging();
					this._CreatedUser = value;
					this.SendPropertyChanged("CreatedUser");
					this.OnCreatedUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedUser", DbType="NVarChar(250)")]
		public string UpdatedUser
		{
			get
			{
				return this._UpdatedUser;
			}
			set
			{
				if ((this._UpdatedUser != value))
				{
					this.OnUpdatedUserChanging(value);
					this.SendPropertyChanging();
					this._UpdatedUser = value;
					this.SendPropertyChanged("UpdatedUser");
					this.OnUpdatedUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chedouutien")]
	public partial class chedouutien
	{
		
		private int _iduutien;
		
		private string _tenuutien;
		
		private System.Nullable<int> _parentId;
		
		public chedouutien()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iduutien", DbType="Int NOT NULL")]
		public int iduutien
		{
			get
			{
				return this._iduutien;
			}
			set
			{
				if ((this._iduutien != value))
				{
					this._iduutien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenuutien", DbType="NVarChar(250)")]
		public string tenuutien
		{
			get
			{
				return this._tenuutien;
			}
			set
			{
				if ((this._tenuutien != value))
				{
					this._tenuutien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentId", DbType="Int")]
		public System.Nullable<int> parentId
		{
			get
			{
				return this._parentId;
			}
			set
			{
				if ((this._parentId != value))
				{
					this._parentId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hocba")]
	public partial class hocba
	{
		
		private int _idhocba;
		
		private string _hocluc;
		
		private string _hanhkiem;
		
		private string _toan;
		
		private string _tienganh;
		
		private string _nguvan;
		
		private string _mahs;
		
		public hocba()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhocba", DbType="Int NOT NULL")]
		public int idhocba
		{
			get
			{
				return this._idhocba;
			}
			set
			{
				if ((this._idhocba != value))
				{
					this._idhocba = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hocluc", DbType="NVarChar(50)")]
		public string hocluc
		{
			get
			{
				return this._hocluc;
			}
			set
			{
				if ((this._hocluc != value))
				{
					this._hocluc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hanhkiem", DbType="NVarChar(50)")]
		public string hanhkiem
		{
			get
			{
				return this._hanhkiem;
			}
			set
			{
				if ((this._hanhkiem != value))
				{
					this._hanhkiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toan", DbType="NVarChar(50)")]
		public string toan
		{
			get
			{
				return this._toan;
			}
			set
			{
				if ((this._toan != value))
				{
					this._toan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienganh", DbType="NVarChar(50)")]
		public string tienganh
		{
			get
			{
				return this._tienganh;
			}
			set
			{
				if ((this._tienganh != value))
				{
					this._tienganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguvan", DbType="NVarChar(50)")]
		public string nguvan
		{
			get
			{
				return this._nguvan;
			}
			set
			{
				if ((this._nguvan != value))
				{
					this._nguvan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahs", DbType="NVarChar(50)")]
		public string mahs
		{
			get
			{
				return this._mahs;
			}
			set
			{
				if ((this._mahs != value))
				{
					this._mahs = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hosodinhkem")]
	public partial class hosodinhkem
	{
		
		private string _idhoso;
		
		private string _giaykhaisinh;
		
		private string _sohokhau;
		
		private string _cacgiaytokhac;
		
		public hosodinhkem()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhoso", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string idhoso
		{
			get
			{
				return this._idhoso;
			}
			set
			{
				if ((this._idhoso != value))
				{
					this._idhoso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaykhaisinh", DbType="NVarChar(250)")]
		public string giaykhaisinh
		{
			get
			{
				return this._giaykhaisinh;
			}
			set
			{
				if ((this._giaykhaisinh != value))
				{
					this._giaykhaisinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sohokhau", DbType="NVarChar(250)")]
		public string sohokhau
		{
			get
			{
				return this._sohokhau;
			}
			set
			{
				if ((this._sohokhau != value))
				{
					this._sohokhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cacgiaytokhac", DbType="NVarChar(250)")]
		public string cacgiaytokhac
		{
			get
			{
				return this._cacgiaytokhac;
			}
			set
			{
				if ((this._cacgiaytokhac != value))
				{
					this._cacgiaytokhac = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thongtinhocsinh")]
	public partial class thongtinhocsinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahs;
		
		private string _matruong;
		
		private string _matkhau;
		
		private string _hoten;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _dantoc;
		
		private System.Nullable<int> _noisinhtp;
		
		private System.Nullable<int> _noisinhquan;
		
		private System.Nullable<int> _tamtrutp;
		
		private System.Nullable<int> _tamtruquan;
		
		private System.Nullable<int> _tamtruxa;
		
		private string _tamtrudiachi;
		
		private System.Nullable<System.DateTime> _tamtrungay;
		
		private System.Nullable<int> _thuongtrutp;
		
		private System.Nullable<int> _thuongtruquan;
		
		private System.Nullable<int> _thuongtruxa;
		
		private string _thuongtrudiachi;
		
		private System.Nullable<System.DateTime> _thuongtrungay;
		
		private System.Nullable<int> _hientaitp;
		
		private System.Nullable<int> _hientaiquan;
		
		private System.Nullable<int> _hientaixa;
		
		private string _hotencha;
		
		private string _nghecha;
		
		private System.Nullable<int> _tuoicha;
		
		private string _congtycha;
		
		private string _sdtcha;
		
		private string _hotenme;
		
		private string _ngheme;
		
		private System.Nullable<int> _tuoime;
		
		private string _congtyme;
		
		private string _sdtme;
		
		private string _hotengiamho;
		
		private string _nghegiamho;
		
		private System.Nullable<int> _tuoigiamho;
		
		private string _congtygiamho;
		
		private string _sdtgiamho;
		
		private string _dtlienhe;
		
		private string _emaillienhe;
		
		private string _iduutien;
		
		private string _idhosodinhkem;
		
		private string _hientaidiachi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahsChanging(string value);
    partial void OnmahsChanged();
    partial void OnmatruongChanging(string value);
    partial void OnmatruongChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndantocChanging(string value);
    partial void OndantocChanged();
    partial void OnnoisinhtpChanging(System.Nullable<int> value);
    partial void OnnoisinhtpChanged();
    partial void OnnoisinhquanChanging(System.Nullable<int> value);
    partial void OnnoisinhquanChanged();
    partial void OntamtrutpChanging(System.Nullable<int> value);
    partial void OntamtrutpChanged();
    partial void OntamtruquanChanging(System.Nullable<int> value);
    partial void OntamtruquanChanged();
    partial void OntamtruxaChanging(System.Nullable<int> value);
    partial void OntamtruxaChanged();
    partial void OntamtrudiachiChanging(string value);
    partial void OntamtrudiachiChanged();
    partial void OntamtrungayChanging(System.Nullable<System.DateTime> value);
    partial void OntamtrungayChanged();
    partial void OnthuongtrutpChanging(System.Nullable<int> value);
    partial void OnthuongtrutpChanged();
    partial void OnthuongtruquanChanging(System.Nullable<int> value);
    partial void OnthuongtruquanChanged();
    partial void OnthuongtruxaChanging(System.Nullable<int> value);
    partial void OnthuongtruxaChanged();
    partial void OnthuongtrudiachiChanging(string value);
    partial void OnthuongtrudiachiChanged();
    partial void OnthuongtrungayChanging(System.Nullable<System.DateTime> value);
    partial void OnthuongtrungayChanged();
    partial void OnhientaitpChanging(System.Nullable<int> value);
    partial void OnhientaitpChanged();
    partial void OnhientaiquanChanging(System.Nullable<int> value);
    partial void OnhientaiquanChanged();
    partial void OnhientaixaChanging(System.Nullable<int> value);
    partial void OnhientaixaChanged();
    partial void OnhotenchaChanging(string value);
    partial void OnhotenchaChanged();
    partial void OnnghechaChanging(string value);
    partial void OnnghechaChanged();
    partial void OntuoichaChanging(System.Nullable<int> value);
    partial void OntuoichaChanged();
    partial void OncongtychaChanging(string value);
    partial void OncongtychaChanged();
    partial void OnsdtchaChanging(string value);
    partial void OnsdtchaChanged();
    partial void OnhotenmeChanging(string value);
    partial void OnhotenmeChanged();
    partial void OnnghemeChanging(string value);
    partial void OnnghemeChanged();
    partial void OntuoimeChanging(System.Nullable<int> value);
    partial void OntuoimeChanged();
    partial void OncongtymeChanging(string value);
    partial void OncongtymeChanged();
    partial void OnsdtmeChanging(string value);
    partial void OnsdtmeChanged();
    partial void OnhotengiamhoChanging(string value);
    partial void OnhotengiamhoChanged();
    partial void OnnghegiamhoChanging(string value);
    partial void OnnghegiamhoChanged();
    partial void OntuoigiamhoChanging(System.Nullable<int> value);
    partial void OntuoigiamhoChanged();
    partial void OncongtygiamhoChanging(string value);
    partial void OncongtygiamhoChanged();
    partial void OnsdtgiamhoChanging(string value);
    partial void OnsdtgiamhoChanged();
    partial void OndtlienheChanging(string value);
    partial void OndtlienheChanged();
    partial void OnemaillienheChanging(string value);
    partial void OnemaillienheChanged();
    partial void OniduutienChanging(string value);
    partial void OniduutienChanged();
    partial void OnidhosodinhkemChanging(string value);
    partial void OnidhosodinhkemChanged();
    partial void OnhientaidiachiChanging(string value);
    partial void OnhientaidiachiChanged();
    #endregion
		
		public thongtinhocsinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahs", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahs
		{
			get
			{
				return this._mahs;
			}
			set
			{
				if ((this._mahs != value))
				{
					this.OnmahsChanging(value);
					this.SendPropertyChanging();
					this._mahs = value;
					this.SendPropertyChanged("mahs");
					this.OnmahsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matruong", DbType="NVarChar(50)")]
		public string matruong
		{
			get
			{
				return this._matruong;
			}
			set
			{
				if ((this._matruong != value))
				{
					this.OnmatruongChanging(value);
					this.SendPropertyChanging();
					this._matruong = value;
					this.SendPropertyChanged("matruong");
					this.OnmatruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(100)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(50)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dantoc", DbType="NVarChar(50)")]
		public string dantoc
		{
			get
			{
				return this._dantoc;
			}
			set
			{
				if ((this._dantoc != value))
				{
					this.OndantocChanging(value);
					this.SendPropertyChanging();
					this._dantoc = value;
					this.SendPropertyChanged("dantoc");
					this.OndantocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noisinhtp", DbType="Int")]
		public System.Nullable<int> noisinhtp
		{
			get
			{
				return this._noisinhtp;
			}
			set
			{
				if ((this._noisinhtp != value))
				{
					this.OnnoisinhtpChanging(value);
					this.SendPropertyChanging();
					this._noisinhtp = value;
					this.SendPropertyChanged("noisinhtp");
					this.OnnoisinhtpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noisinhquan", DbType="Int")]
		public System.Nullable<int> noisinhquan
		{
			get
			{
				return this._noisinhquan;
			}
			set
			{
				if ((this._noisinhquan != value))
				{
					this.OnnoisinhquanChanging(value);
					this.SendPropertyChanging();
					this._noisinhquan = value;
					this.SendPropertyChanged("noisinhquan");
					this.OnnoisinhquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamtrutp", DbType="Int")]
		public System.Nullable<int> tamtrutp
		{
			get
			{
				return this._tamtrutp;
			}
			set
			{
				if ((this._tamtrutp != value))
				{
					this.OntamtrutpChanging(value);
					this.SendPropertyChanging();
					this._tamtrutp = value;
					this.SendPropertyChanged("tamtrutp");
					this.OntamtrutpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamtruquan", DbType="Int")]
		public System.Nullable<int> tamtruquan
		{
			get
			{
				return this._tamtruquan;
			}
			set
			{
				if ((this._tamtruquan != value))
				{
					this.OntamtruquanChanging(value);
					this.SendPropertyChanging();
					this._tamtruquan = value;
					this.SendPropertyChanged("tamtruquan");
					this.OntamtruquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamtruxa", DbType="Int")]
		public System.Nullable<int> tamtruxa
		{
			get
			{
				return this._tamtruxa;
			}
			set
			{
				if ((this._tamtruxa != value))
				{
					this.OntamtruxaChanging(value);
					this.SendPropertyChanging();
					this._tamtruxa = value;
					this.SendPropertyChanged("tamtruxa");
					this.OntamtruxaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamtrudiachi", DbType="NVarChar(250)")]
		public string tamtrudiachi
		{
			get
			{
				return this._tamtrudiachi;
			}
			set
			{
				if ((this._tamtrudiachi != value))
				{
					this.OntamtrudiachiChanging(value);
					this.SendPropertyChanging();
					this._tamtrudiachi = value;
					this.SendPropertyChanged("tamtrudiachi");
					this.OntamtrudiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamtrungay", DbType="DateTime")]
		public System.Nullable<System.DateTime> tamtrungay
		{
			get
			{
				return this._tamtrungay;
			}
			set
			{
				if ((this._tamtrungay != value))
				{
					this.OntamtrungayChanging(value);
					this.SendPropertyChanging();
					this._tamtrungay = value;
					this.SendPropertyChanged("tamtrungay");
					this.OntamtrungayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuongtrutp", DbType="Int")]
		public System.Nullable<int> thuongtrutp
		{
			get
			{
				return this._thuongtrutp;
			}
			set
			{
				if ((this._thuongtrutp != value))
				{
					this.OnthuongtrutpChanging(value);
					this.SendPropertyChanging();
					this._thuongtrutp = value;
					this.SendPropertyChanged("thuongtrutp");
					this.OnthuongtrutpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuongtruquan", DbType="Int")]
		public System.Nullable<int> thuongtruquan
		{
			get
			{
				return this._thuongtruquan;
			}
			set
			{
				if ((this._thuongtruquan != value))
				{
					this.OnthuongtruquanChanging(value);
					this.SendPropertyChanging();
					this._thuongtruquan = value;
					this.SendPropertyChanged("thuongtruquan");
					this.OnthuongtruquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuongtruxa", DbType="Int")]
		public System.Nullable<int> thuongtruxa
		{
			get
			{
				return this._thuongtruxa;
			}
			set
			{
				if ((this._thuongtruxa != value))
				{
					this.OnthuongtruxaChanging(value);
					this.SendPropertyChanging();
					this._thuongtruxa = value;
					this.SendPropertyChanged("thuongtruxa");
					this.OnthuongtruxaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuongtrudiachi", DbType="NVarChar(250)")]
		public string thuongtrudiachi
		{
			get
			{
				return this._thuongtrudiachi;
			}
			set
			{
				if ((this._thuongtrudiachi != value))
				{
					this.OnthuongtrudiachiChanging(value);
					this.SendPropertyChanging();
					this._thuongtrudiachi = value;
					this.SendPropertyChanged("thuongtrudiachi");
					this.OnthuongtrudiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuongtrungay", DbType="DateTime")]
		public System.Nullable<System.DateTime> thuongtrungay
		{
			get
			{
				return this._thuongtrungay;
			}
			set
			{
				if ((this._thuongtrungay != value))
				{
					this.OnthuongtrungayChanging(value);
					this.SendPropertyChanging();
					this._thuongtrungay = value;
					this.SendPropertyChanged("thuongtrungay");
					this.OnthuongtrungayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hientaitp", DbType="Int")]
		public System.Nullable<int> hientaitp
		{
			get
			{
				return this._hientaitp;
			}
			set
			{
				if ((this._hientaitp != value))
				{
					this.OnhientaitpChanging(value);
					this.SendPropertyChanging();
					this._hientaitp = value;
					this.SendPropertyChanged("hientaitp");
					this.OnhientaitpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hientaiquan", DbType="Int")]
		public System.Nullable<int> hientaiquan
		{
			get
			{
				return this._hientaiquan;
			}
			set
			{
				if ((this._hientaiquan != value))
				{
					this.OnhientaiquanChanging(value);
					this.SendPropertyChanging();
					this._hientaiquan = value;
					this.SendPropertyChanged("hientaiquan");
					this.OnhientaiquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hientaixa", DbType="Int")]
		public System.Nullable<int> hientaixa
		{
			get
			{
				return this._hientaixa;
			}
			set
			{
				if ((this._hientaixa != value))
				{
					this.OnhientaixaChanging(value);
					this.SendPropertyChanging();
					this._hientaixa = value;
					this.SendPropertyChanged("hientaixa");
					this.OnhientaixaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotencha", DbType="NVarChar(250)")]
		public string hotencha
		{
			get
			{
				return this._hotencha;
			}
			set
			{
				if ((this._hotencha != value))
				{
					this.OnhotenchaChanging(value);
					this.SendPropertyChanging();
					this._hotencha = value;
					this.SendPropertyChanged("hotencha");
					this.OnhotenchaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nghecha", DbType="NVarChar(250)")]
		public string nghecha
		{
			get
			{
				return this._nghecha;
			}
			set
			{
				if ((this._nghecha != value))
				{
					this.OnnghechaChanging(value);
					this.SendPropertyChanging();
					this._nghecha = value;
					this.SendPropertyChanged("nghecha");
					this.OnnghechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuoicha", DbType="Int")]
		public System.Nullable<int> tuoicha
		{
			get
			{
				return this._tuoicha;
			}
			set
			{
				if ((this._tuoicha != value))
				{
					this.OntuoichaChanging(value);
					this.SendPropertyChanging();
					this._tuoicha = value;
					this.SendPropertyChanged("tuoicha");
					this.OntuoichaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congtycha", DbType="NVarChar(250)")]
		public string congtycha
		{
			get
			{
				return this._congtycha;
			}
			set
			{
				if ((this._congtycha != value))
				{
					this.OncongtychaChanging(value);
					this.SendPropertyChanging();
					this._congtycha = value;
					this.SendPropertyChanged("congtycha");
					this.OncongtychaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtcha", DbType="NVarChar(250)")]
		public string sdtcha
		{
			get
			{
				return this._sdtcha;
			}
			set
			{
				if ((this._sdtcha != value))
				{
					this.OnsdtchaChanging(value);
					this.SendPropertyChanging();
					this._sdtcha = value;
					this.SendPropertyChanged("sdtcha");
					this.OnsdtchaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotenme", DbType="NVarChar(250)")]
		public string hotenme
		{
			get
			{
				return this._hotenme;
			}
			set
			{
				if ((this._hotenme != value))
				{
					this.OnhotenmeChanging(value);
					this.SendPropertyChanging();
					this._hotenme = value;
					this.SendPropertyChanged("hotenme");
					this.OnhotenmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngheme", DbType="NVarChar(250)")]
		public string ngheme
		{
			get
			{
				return this._ngheme;
			}
			set
			{
				if ((this._ngheme != value))
				{
					this.OnnghemeChanging(value);
					this.SendPropertyChanging();
					this._ngheme = value;
					this.SendPropertyChanged("ngheme");
					this.OnnghemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuoime", DbType="Int")]
		public System.Nullable<int> tuoime
		{
			get
			{
				return this._tuoime;
			}
			set
			{
				if ((this._tuoime != value))
				{
					this.OntuoimeChanging(value);
					this.SendPropertyChanging();
					this._tuoime = value;
					this.SendPropertyChanged("tuoime");
					this.OntuoimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congtyme", DbType="NVarChar(250)")]
		public string congtyme
		{
			get
			{
				return this._congtyme;
			}
			set
			{
				if ((this._congtyme != value))
				{
					this.OncongtymeChanging(value);
					this.SendPropertyChanging();
					this._congtyme = value;
					this.SendPropertyChanged("congtyme");
					this.OncongtymeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtme", DbType="NVarChar(250)")]
		public string sdtme
		{
			get
			{
				return this._sdtme;
			}
			set
			{
				if ((this._sdtme != value))
				{
					this.OnsdtmeChanging(value);
					this.SendPropertyChanging();
					this._sdtme = value;
					this.SendPropertyChanged("sdtme");
					this.OnsdtmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotengiamho", DbType="NVarChar(250)")]
		public string hotengiamho
		{
			get
			{
				return this._hotengiamho;
			}
			set
			{
				if ((this._hotengiamho != value))
				{
					this.OnhotengiamhoChanging(value);
					this.SendPropertyChanging();
					this._hotengiamho = value;
					this.SendPropertyChanged("hotengiamho");
					this.OnhotengiamhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nghegiamho", DbType="NVarChar(250)")]
		public string nghegiamho
		{
			get
			{
				return this._nghegiamho;
			}
			set
			{
				if ((this._nghegiamho != value))
				{
					this.OnnghegiamhoChanging(value);
					this.SendPropertyChanging();
					this._nghegiamho = value;
					this.SendPropertyChanged("nghegiamho");
					this.OnnghegiamhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuoigiamho", DbType="Int")]
		public System.Nullable<int> tuoigiamho
		{
			get
			{
				return this._tuoigiamho;
			}
			set
			{
				if ((this._tuoigiamho != value))
				{
					this.OntuoigiamhoChanging(value);
					this.SendPropertyChanging();
					this._tuoigiamho = value;
					this.SendPropertyChanged("tuoigiamho");
					this.OntuoigiamhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_congtygiamho", DbType="NVarChar(250)")]
		public string congtygiamho
		{
			get
			{
				return this._congtygiamho;
			}
			set
			{
				if ((this._congtygiamho != value))
				{
					this.OncongtygiamhoChanging(value);
					this.SendPropertyChanging();
					this._congtygiamho = value;
					this.SendPropertyChanged("congtygiamho");
					this.OncongtygiamhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtgiamho", DbType="NVarChar(250)")]
		public string sdtgiamho
		{
			get
			{
				return this._sdtgiamho;
			}
			set
			{
				if ((this._sdtgiamho != value))
				{
					this.OnsdtgiamhoChanging(value);
					this.SendPropertyChanging();
					this._sdtgiamho = value;
					this.SendPropertyChanged("sdtgiamho");
					this.OnsdtgiamhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtlienhe", DbType="NVarChar(250)")]
		public string dtlienhe
		{
			get
			{
				return this._dtlienhe;
			}
			set
			{
				if ((this._dtlienhe != value))
				{
					this.OndtlienheChanging(value);
					this.SendPropertyChanging();
					this._dtlienhe = value;
					this.SendPropertyChanged("dtlienhe");
					this.OndtlienheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emaillienhe", DbType="NVarChar(250)")]
		public string emaillienhe
		{
			get
			{
				return this._emaillienhe;
			}
			set
			{
				if ((this._emaillienhe != value))
				{
					this.OnemaillienheChanging(value);
					this.SendPropertyChanging();
					this._emaillienhe = value;
					this.SendPropertyChanged("emaillienhe");
					this.OnemaillienheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iduutien", DbType="NVarChar(50)")]
		public string iduutien
		{
			get
			{
				return this._iduutien;
			}
			set
			{
				if ((this._iduutien != value))
				{
					this.OniduutienChanging(value);
					this.SendPropertyChanging();
					this._iduutien = value;
					this.SendPropertyChanged("iduutien");
					this.OniduutienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idhosodinhkem", DbType="NVarChar(250)")]
		public string idhosodinhkem
		{
			get
			{
				return this._idhosodinhkem;
			}
			set
			{
				if ((this._idhosodinhkem != value))
				{
					this.OnidhosodinhkemChanging(value);
					this.SendPropertyChanging();
					this._idhosodinhkem = value;
					this.SendPropertyChanged("idhosodinhkem");
					this.OnidhosodinhkemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hientaidiachi", DbType="NVarChar(250)")]
		public string hientaidiachi
		{
			get
			{
				return this._hientaidiachi;
			}
			set
			{
				if ((this._hientaidiachi != value))
				{
					this.OnhientaidiachiChanging(value);
					this.SendPropertyChanging();
					this._hientaidiachi = value;
					this.SendPropertyChanged("hientaidiachi");
					this.OnhientaidiachiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileInfo")]
	public partial class FileInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _idfile;
		
		private string _urlfile;
		
		private string _namefile;
		
		private string _sizefile;
		
		private string _extfile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidfileChanging(long value);
    partial void OnidfileChanged();
    partial void OnurlfileChanging(string value);
    partial void OnurlfileChanged();
    partial void OnnamefileChanging(string value);
    partial void OnnamefileChanged();
    partial void OnsizefileChanging(string value);
    partial void OnsizefileChanged();
    partial void OnextfileChanging(string value);
    partial void OnextfileChanged();
    #endregion
		
		public FileInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idfile", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long idfile
		{
			get
			{
				return this._idfile;
			}
			set
			{
				if ((this._idfile != value))
				{
					this.OnidfileChanging(value);
					this.SendPropertyChanging();
					this._idfile = value;
					this.SendPropertyChanged("idfile");
					this.OnidfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlfile", DbType="NVarChar(250)")]
		public string urlfile
		{
			get
			{
				return this._urlfile;
			}
			set
			{
				if ((this._urlfile != value))
				{
					this.OnurlfileChanging(value);
					this.SendPropertyChanging();
					this._urlfile = value;
					this.SendPropertyChanged("urlfile");
					this.OnurlfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namefile", DbType="NVarChar(250)")]
		public string namefile
		{
			get
			{
				return this._namefile;
			}
			set
			{
				if ((this._namefile != value))
				{
					this.OnnamefileChanging(value);
					this.SendPropertyChanging();
					this._namefile = value;
					this.SendPropertyChanged("namefile");
					this.OnnamefileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sizefile", DbType="NVarChar(250)")]
		public string sizefile
		{
			get
			{
				return this._sizefile;
			}
			set
			{
				if ((this._sizefile != value))
				{
					this.OnsizefileChanging(value);
					this.SendPropertyChanging();
					this._sizefile = value;
					this.SendPropertyChanged("sizefile");
					this.OnsizefileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extfile", DbType="NVarChar(250)")]
		public string extfile
		{
			get
			{
				return this._extfile;
			}
			set
			{
				if ((this._extfile != value))
				{
					this.OnextfileChanging(value);
					this.SendPropertyChanging();
					this._extfile = value;
					this.SendPropertyChanged("extfile");
					this.OnextfileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
